# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
